### PR TITLE
Prefer initializers over global variables in Ember

### PR DESCRIPTION
**Pull request by BlakeWilliams**
Prefer to use initializers and dependency injection when dealing with "global" data in Ember.

eg: Storing the current user.

### CODE REVIEW

**Comment by jferris** [comment]
> It's specific to Ember since you should be injecting them via initializers when possible.

It seems like the "Avoid global variables" part is a generic programming guideline. Maybe just the part about avoiding `window` is useful, since that doesn't *seem* global but it is?

**Comment by BlakeWilliams** [comment]
The point here is to encourage more use of [initializers](http://emberjs.com/api/classes/Ember.Application.html#toc_initializers). I still see a lot of information put on `window` and `App` when Ember lets you inject it where you need it specifically.

**Comment by BlakeWilliams** [comment]
Maybe 
> Prefer dependency injection through Ember initializers over `window` and namespaces?

**Comment by jferris** [comment]
@BlakeWilliams your latest comment seems clearer to me. Want to push an update?

**Comment by BlakeWilliams** [comment]
@jferris Yep, doing it now.

**Comment by BlakeWilliams** [comment]
Any more thoughts before I merge this?

**Comment by JoelQ** [comment]
:+1:

**Pull request merged**
