### PR TITLE
Add guidance on sharing pronouns

### PR DESCRIPTION
**Pull request by sallyhall**
Adds the guidance from the hub message on sharing pronouns to guides. Step 2 is to link to this from the playbook once this is merged.

### CODE REVIEW

**Review by mike-burns — APPROVED** [review]
So, this LGTM, but I have logistical questions.

How is the Playbook generated? Is it from the Handbook? Can we put this directly into the Playbook?

Sorry, I should know these things.

**Comment by SViccari** [comment]
@sallyhall Thank you for adding this. 💛

Following up on your comment in Hub: https://hub.thoughtbot.com/messages/sharing-pronouns-is-always-optional#comment_25458

I looked at the playbook and I agree, I'm having trouble discerning the right place for this information. 

Here are two ideas:
1. In the Playbook, under Planning, repurpose the page titled ["A functioning remote team doesn't happen by accident"](https://thoughtbot.com/playbook/planning/working-remotely) to a more general "working together" theme. For example, we could re-purpose this page to "A functioning team doesn't happen by accident" or "Team Collaboration". Then, we could include a section titled "Pronoun guidelines". This would also create space for us to link to [Pair Programming Guidelines](https://github.com/thoughtbot/guides/blob/main/working-together/README.md#pair-programming) and [In-Person Meetings](https://github.com/thoughtbot/guides/blob/main/working-together/README.md#in-person-meeting-guidelines). 
2. Add "Pronoun guidelines" to the Playbook under the Our Company -> [Diversity, Equity, and Inclusion](https://thoughtbot.com/playbook/our-company/diversity-equity-and-inclusion)

**Comment by SViccari** [comment]
@mike-burns 

> How is the Playbook generated? Is it from the Handbook?

Yes, the Playbook is generated from the Handbook. Example:
1. This [page](https://thoughtbot.com/playbook/planning/working-remotely) in the Playbook includes a link to our "Remote Meeting Guidelines". 
2. These guidelines in the live in the [Guides repo](https://github.com/thoughtbot/guides/blob/main/working-together/README.md#remote-meeting-guidelines). 
3. In the [Handbook/playbook](https://github.com/thoughtbot/handbook/blob/4b33bf8fc64a4ff63e2f2418477a883b940cfa7e/playbook/planning/working-remotely.md#inclusive-remote-meeting-guidelines), we link to the Guides repo "Remote Meeting Guidelines". 
4. The [Handbook/playbook content](https://github.com/thoughtbot/handbook/tree/4b33bf8fc64a4ff63e2f2418477a883b940cfa7e/playbook) is then published to the Playbook website. 

> Can we put this directly into the Playbook?

What lives in Guides vs the Handbook is a bit fuzzy to me. The nicety of adding to Guides is everything is public by default. I don't feel strongly about whether this content lives in Guides vs in the Handbook/playbook.

**Review by dorianmariefr — APPROVED** [review]

**Review by thoughtbot-summer — APPROVED** [review]

**Comment by sallyhall** [comment]
I'm going to merge this as-is, since I've been avoiding finding a better location for it for over 90 days now and I'd rather have it in than have it perfect. I'm hoping to find bandwidth to figure out how to get it into the playbook soon, but Im not 100% sure when that will happen.

**Pull request merged**
