### PR TITLE
Remove guideline for recommended css file structure.

### PR DESCRIPTION
**Pull request by brendastorer**
I don't think this is considered a best practice anymore, and this isn't a guideline I follow. File structure for CSS is moving towards styling modules/components that can be reused anywhere vs. per page or view. This can cut down on repeated code for similar styles across views, and also helps maintain consistency in design across a site.

### CODE REVIEW

**Comment by carolanncan** [comment]
Agreed. :+1:

**Comment by kylefiedler** [comment]
@brendastorer I agree but I want you to replace it another (or multiple) guideline on how we should be structuring our Sass files.

**Comment by kylefiedler** [comment]
This might be a good starting point: http://sass-guidelin.es/#architecture

**Comment by brendastorer** [comment]
Good idea @kylefiedler Thanks!

**Comment by jferris** [comment]
If it's not possible to swap in a new recommendation quickly, it seems like it would be worth merging this as-is. It seems to me that it's worse to provide bad advice than to provide no advice at all.

**Comment by jferris** [comment]
@kylefiedler @brendastorer any updates here?

**Comment by brendastorer** [comment]
I would like to merge it in as is, because we definitely don't need this guideline, and then take some time to make a researched and collaborative PR with an update to how we should organize the file structure.

**Comment by joshuaogle** [comment]
:+1: For merging. I would love to see a card on the Research board for suggested organization if someone has a system in mind.

**Comment by brendastorer** [comment]
Thanks all. @joshuaogle great suggestions. Card created and can be found here: https://trello.com/c/0YAPIBso/448-best-practices-for-css-sass-file-structure Merging in as is.

**Pull request merged**
