### PR TITLE
Fix dead link in Best Practices

### PR DESCRIPTION
**Pull request by jontonsoup**
Fix dead link for "Exceptions should be exceptional"

### CODE REVIEW

**Comment by jferris** [comment]
Is this what we were originally linking to here? I don't even know!

I wonder if something like Stack Exchange is a better target. This is a continual discussion: http://programmers.stackexchange.com/questions/184654/ive-been-told-that-exceptions-should-only-be-used-in-exceptional-cases-how-do

Anybody have thoughts on this?

**Comment by mjankowski** [comment]
The original thing went to tip 34 in "The Pragmatic Programmer", which is "Use Exceptions for Exceptional Problems"

It's down this page somewhere: https://pragprog.com/the-pragmatic-programmer/extracts/tips

I can't find a place which provides the full excerpt from TPP, and I don't remember if that's what the original link did. Maybe.

**Comment by jferris** [comment]
I'm leaning towards just removing this link. Realistically, if you don't understand the guide line, you need to Google it.

Thoughts?

**Comment by mjankowski** [comment]
I hereby authorize you to delete this link.

**Comment by jferris** [comment]
Deleted!

**Comment by graysonwright** [comment]
https://github.com/thoughtbot/guides/commit/c95ba094b5c897c2d83b5f6ddee6e3995d14d862

**Pull request closed without merging**
