### PR TITLE
Update our Android best practices

### PR DESCRIPTION
**Pull request by mike-burns**
More to come, but these are the basics for Android development in the
year 2020.

### CODE REVIEW

**Comment by mike-burns** [comment]
@JadeByfield89 thoughts? is there anything simple and non-controversial that we should add now?

**Comment by JadeByfield89** [comment]
This is a solid list @mike-burns. Do we want to suggest that devs use a design pattern, or is that already implied?

Also, a couple suggestions

- Use string resources wherever possible
- Use vector drawables over PNGs or JPGs wherever possible

**Comment by mike-burns** [comment]
Those two suggestions are perfect. I'll add them.

> Do we want to suggest that devs use a design pattern

I'll make a separate PR declaring that we should use MVVM for everything. There's a chance of disagreement and I'd like to contain that discussion there.

**Comment by mike-burns** [comment]
MVVM: https://github.com/thoughtbot/guides/pull/626

**Pull request merged**
