### PR TITLE
Prefer `if` over `unless`

### PR DESCRIPTION
**Pull request by gabebw**

### CODE REVIEW

**Comment by jferris** [comment]
Are there any objections to moving this into the "Style" section, since the behavior is the same?

*Pedantry: you can override `!` in Ruby, so `if ! foo` and `unless foo` are technically not identical.*

**Comment by teoljungberg** [comment]
Aslong as we just _prefer_ `if` over `unless`, I'll :+1:

**Comment by gabebw** [comment]
If I move this as-is ("Prefer if to unless") to the style section, any objections?

**Comment by mike-burns** [comment]
Works for me.

**Comment by BlakeWilliams** [comment]
:+1: to style section

**Comment by jferris** [comment]
@gabebw looks like this has been open for a week without objection. Ready to merge.

**Pull request merged**
