### PR TITLE
Add foreign key constraints Rails in migrations

### PR DESCRIPTION
**Pull request by croaky**

### CODE REVIEW

**Comment by jferris** [comment]
This seems like a good idea to me.

**Comment by derekprior** [comment]
:+1:

**Comment by sikachu** [comment]
:+1:

**Comment by mcmire** [comment]
I approve of this in theory, but I haven't actually tried this yet, so I can't say whether I'd approve of this in practice. Are there any pain points with adding constraints like this?

**Comment by sikachu** [comment]
@mcmire no, but there's pain point when this constraint is _missing_.

**Comment by derekprior** [comment]
When I add these some times shoulda-matcher type specs fail. Like if you're validating uniqueness on a FK column or something. You just have to create a record beforehand.

**Comment by jferris** [comment]
Let's merge this!

**Comment by srt32** [comment]
:+1:

**Comment by croaky** [comment]
Okay!

**Pull request merged**
