### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by steve-dixon**

### CODE REVIEW

**Comment by jferris** [comment]
@steve-dixon want to merge this?

**Comment by steve-dixon** [comment]
Done!

**Comment by jferris** [comment]
> Done!

Are you sure??! I can't see your commit on master.

**Comment by steve-dixon** [comment]
Yeah, it's taking a while to show up. I merged in the GitHub for Mac app.

**Comment by jferris** [comment]
I think you may need to push/synchronize. It seems like the merge only occurred in your local Git clone.

**Comment by steve-dixon** [comment]
Thanks @jferris. GitHub for Mac was messing up on me.

**Pull request merged**
