### PR TITLE
Use 2 spaces for swift

### PR DESCRIPTION
**Pull request by Keithbsmiley**
I think we should use 2 spaces for Swift code. Thoughts?

### CODE REVIEW

**Comment by jferris** [comment]
Anything else to add here?

**Comment by dazmuda** [comment]
My 2cents: If the guides are a guideline for writing code like we write at thoughtbot, I like 2 spaces and think this should be in. However, I like to think of guides as a "best practices" type thing, which makes me think that since this is a preference it shouldn't be in. My gut says the latter.

**Comment by gfontenot** [comment]
If more people like 2 spaces than 4, I'm OK with this. It seems like @jnutting and I are the only dissenters.

**Comment by Keithbsmiley** [comment]
I think, that since this isn't unanimous, I should just close this. Since what will probably happen is people who don't like 2 spaces will keep using 4 and this PR won't mean anything.

**Pull request closed without merging**
