### PR TITLE
Add rule for factory_girl trait ordering

### PR DESCRIPTION
**Pull request by rupurt**

### CODE REVIEW

**Comment by mcmire** [comment]
Seems like a good guideline to me, anyone have any feedback on this?

**Comment by drapergeek** [comment]
I can't think of an argument against this, :+1:

**Comment by gabebw** [comment]
:+1:

**Comment by jakecraige** [comment]
> I can't think of an argument against this

Is there an argument for this? 

Personally I'm against most(all?) alphabetical guidelines. The second someone breaks it you have major diff noise. This also adds extra strain on me to have to manually alphabetize things when I add something since I can't `:sort` it easily. 

I'm :-1:

**Comment by rupurt** [comment]
@jakecraige pretty much to keep consistency within the styleguide. Is there a styleguide for the styleguide? ;P

**Comment by mike-burns** [comment]
I see no value in this.

**Comment by jakecraige** [comment]
@rupurt Do you mean the ones above this?

> Order factory attributes: implicit attributes, explicit attributes, child factory definitions. Each section's attributes are alphabetical.
> Order factory definitions alphabetically by factory name.

If so, I kind of want to open a PR to remove those lines, lol.

**Comment by rupurt** [comment]
@jakecraige yes and lolz

**Comment by BlakeWilliams** [comment]
@jakecraige I'd also be in favor of removing those lines.

**Comment by sikachu** [comment]
I see no value in this. 😐

**Comment by teoljungberg** [comment]
There seems to be a majority voting against this. If no-one objects, I'm closing this

**Pull request closed without merging**
