### PR TITLE
Fix links in the README.md file

### PR DESCRIPTION
**Pull request by joseVFernandez**
Changes from relative links to absolute ones

### CODE REVIEW

**Comment by iwz** [comment]
Thanks for spotting this!

Instead of absolute URLs, I wonder if relative URLs like `./` would work?

**Comment by joseVFernandez** [comment]
Let me try! :)

**Comment by joseVFernandez** [comment]
@iwz indeed ```./``` work! PR updated :)

**Comment by iwz** [comment]
Thanks, Jose!

**Pull request merged**
