### PR TITLE
update single line string interpolation wording

### PR DESCRIPTION
**Pull request by bfauble**
update single line string interpolation wording to be less ambiguous as to what it's referring to.

### CODE REVIEW

**Comment by gylaz** [comment]
Referencing #487 for more context.

**Comment by mike-burns** [comment]
How about something like:

> Prefer `"` or `%{}` for strings.

This leaves it up to the dev to decide which of the two options look best.

**Comment by cpytel** [comment]
This has been sitting for a while. Can we either decide to revise before merging, merging without revision, or closing without merging?

**Comment by geoffharcourt** [comment]
@bfauble I rebased, cleaned up the conflict, and merged as fd3cb02. Thank you for your contribution!

**Pull request closed without merging**
