### PR TITLE
Update CI guidance, remove recommendation to use specific service

### PR DESCRIPTION
**Pull request by tysongach**
We tend to use CircleCI over Travis CI, as is [documented in our Handbook](https://github.com/thoughtbot/handbook/blob/master/developing/continuous-integration.md).

### CODE REVIEW

**Comment by tysongach** [comment]
@nickcharlton Yeah, that’s a good point and I had a bit of hesitation about that, as well. I did remember that the readme describes the “Use” language as a “positive instruction”, and that sat nicely with me.

**Comment by paulcsmith** [comment]
I may be an outlier but I've had worse and worse experiences setting up Circle lately and have had better and better experiences with Travis.

The new Circle 2.0 config and UI has been pretty painful to implement. I personally would prefer to keep it as Travis or maybe suggest both depending on team preference

**Comment by mike-burns** [comment]
Historical: we once talked at extreme length about these two, and I don't understand where it ended: https://trello.com/c/GWgWRiBU/280-replace-travis-with-circle

**Comment by paulcsmith** [comment]
@tysongach I think that makes sense. Maybe adding a suggestion would be nice, but I think the team would be the best at making a final decision. So maybe something like `Use continuous integration (CI). Some CI services we've used and recommend are Circle CI and Travis`?

**Comment by jferris** [comment]
I agree that recommending continuous integration (and maybe integration with the code review process) is more important than the specific service.

**Comment by tysongach** [comment]
I’m planning to merge this by the end of today unless people have objections.

**Pull request merged**
