### PR TITLE
Guard against bad `guard` syntax

### PR DESCRIPTION
**Pull request by tonyd256**
Suggest formatting for dealing with `guard` syntax in Swift.

### CODE REVIEW

**Comment by gfontenot** [comment]
ping @thoughtbot/ios

**Comment by gfontenot** [comment]
I think this makes sense.

**Comment by jakecraige** [comment]
Should we also add this to the `README.md` so that people scanning the readme can see this rule exists?

**Comment by seanpdoyle** [comment]
Is there a way to codify this guideline in a [SwiftLint](https://houndci.com/configuration#swift) rule?

**Comment by kaishin** [comment]
Looking good.

**Comment by dgalarza** [comment]
I agree with @jakecraige, is there some way we can link to this in the `README.md`? I feel like people may not notice this otherwise.

**Comment by dazmuda** [comment]
That second case still looks so weird to me but it's the best there is! Ya!

**Comment by tonyd256** [comment]
Xcode wants to indent guards like that but we could do it this way instead if people like:

```
guard let oneItem = somethingFailable(),
  let secondItem = somethingFailable2()
else { return }
```

**Comment by dazmuda** [comment]
Naw man, Xcode's spacing FTW simply because manually managing spacing is a fool's errand.

**Comment by tonyd256** [comment]
@gfontenot if there are no more comments on this tomorrow feel free to merge it in my stead.

**Comment by gfontenot** [comment]
@jakecraige @dgalarza I think this falls under the "break long lines at 100 characters" rule. Maybe we could just add a `// MARK:` section to the sample that has style recommendations for how to break up long lines?

**Comment by dgalarza** [comment]
I like that idea @gfontenot.

**Comment by gfontenot** [comment]
I'll merge this then, and open a new PR to reorganize the sample.

**Pull request merged**
